name: english_boli
description: English speaking learning app for Bangla speakers.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/data/levels/

flutter_native_splash:
  color: "#08100E"
  fullscreen: true

  android_12:
    color: "#08100E"